# Generated by Django 3.2 on 2023-04-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_check_up_reservoir_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrant',
            name='pressure',
        ),
        migrations.AddField(
            model_name='check_up_hydrant',
            name='pressure',
            field=models.IntegerField(default=0),
        ),
    ]
