# Generated by Django 3.2 on 2023-04-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_check_up_hydrant_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_up_reservoir',
            name='pressure',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='check_up_hydrant',
            name='pressure',
            field=models.FloatField(default=0),
        ),
    ]
