# Generated by Django 3.2 on 2023-04-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20230415_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_up_reservoir',
            old_name='pressure',
            new_name='distance',
        ),
    ]
