# Generated by Django 3.2 on 2023-04-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_pressure_check_up_reservoir_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_up_reservoir',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
